import ImageClass from 'assets/heroClassIcon'
import ItemIcon from 'assets/itemIcon'

export const BUTTON_LIST = ['Basic', 'Combo']

export const BASIC_ITEM_LIST = {
  name: 'items',
  type: 'checkbox',
  data: [
    { name: '1', label: 'Dirk', icon: ItemIcon.item1 },
    { name: '2', label: 'Wooden Bow', icon: ItemIcon.item2 },
    { name: '3', label: `Voodoo Wand`, icon: ItemIcon.item3 },
    { name: '4', label: `Shiira's Teardrop`, icon: ItemIcon.item4 },
    { name: '5', label: `Leather Armor`, icon: ItemIcon.item5 },
    { name: '6', label: `Ancestor's Gift`, icon: ItemIcon.item6 },
    { name: '7', label: 'Belt of Pirates', icon: ItemIcon.item7 },
    { name: '8', label: 'Gloves of Loyalty', icon: ItemIcon.item8 },
  ],
}

export const COMBO_ITEM_LIST = {
  name: 'items',
  type: 'checkbox',
  data: [
    { name: '9', label: 'Destiny Blade', icon: ItemIcon.item9 },
    { name: '10', label: 'Bone Crusher', icon: ItemIcon.item10 },
    { name: '11', label: 'Jambiya', icon: ItemIcon.item11 },
    { name: '12', label: 'Restorer', icon: ItemIcon.item12 },
    { name: '13', label: 'Medallium', icon: ItemIcon.item13 },
    { name: '14', label: 'Pyke', icon: ItemIcon.item14 },
    { name: '15', label: 'Moment of Courage', icon: ItemIcon.item15 },
    { name: '16', label: 'Heartbreaker', icon: ItemIcon.item16 },
    { name: '17', label: 'Alphatic Firepower', icon: ItemIcon.item17 },
    { name: '18', label: 'Zeal blade', icon: ItemIcon.item18 },
    { name: '19', label: 'Discipline', icon: ItemIcon.item19 },
    { name: '20', label: 'Dragon Band', icon: ItemIcon.item20 },
    { name: '21', label: 'Balista', icon: ItemIcon.item21 },
    { name: '22', label: 'Gem of Memories', icon: ItemIcon.item22 },
    { name: '23', label: 'Wingfield', icon: ItemIcon.item23 },
    { name: '24', label: 'Magician Cape', icon: ItemIcon.item24 },
    { name: '25', label: 'Fortune Striker', icon: ItemIcon.item25 },
    { name: '26', label: 'Gigamesh', icon: ItemIcon.item26 },
    { name: '27', label: 'Merlini Scepter', icon: ItemIcon.item27 },
    { name: '28', label: 'Sacred Tome', icon: ItemIcon.item28 },
    { name: '29', label: 'Vasterclaw', icon: ItemIcon.item29 },
    { name: '30', label: 'Aeon Duster', icon: ItemIcon.item30 },
    { name: '31', label: 'Lotus Sphere', icon: ItemIcon.item31 },
    { name: '32', label: 'Heavenly Grace', icon: ItemIcon.item32 },
    { name: '33', label: `Hero's Pendant`, icon: ItemIcon.item33 },
    { name: '34', label: 'Pawist', icon: ItemIcon.item34 },
    { name: '35', label: 'Bloodborn', icon: ItemIcon.item35 },
    { name: '36', label: 'Fairy Slasher', icon: ItemIcon.item36 },
    { name: '37', label: 'Defiance', icon: ItemIcon.item37 },
    { name: '38', label: 'Horn Soul', icon: ItemIcon.item38 },
    { name: '39', label: `Ancestor's Faith`, icon: ItemIcon.item39 },
    { name: '40', label: 'Wind Dancer', icon: ItemIcon.item40 },
    { name: '41', label: 'Cloak of Invincibility', icon: ItemIcon.item41 },
    { name: '42', label: 'Void Cuirass', icon: ItemIcon.item42 },
    { name: '43', label: ' Void Harmony', icon: ItemIcon.item43 },
    { name: '44', label: 'Void Gauntlet', icon: ItemIcon.item44 },
  ],
}

// export const COMBO_ITEM_LIST = [
//   { name: '9', icon: ItemIcon.item9 },
//   { name: '10', icon: ItemIcon.item10 },
//   { name: '11', icon: ItemIcon.item11 },
//   { name: '12', icon: ItemIcon.item12 },
//   { name: '13', icon: ItemIcon.item13 },
//   { name: '14', icon: ItemIcon.item14 },
//   { name: '15', icon: ItemIcon.item15 },
//   { name: '16', icon: ItemIcon.item16 },
//   { name: '17', icon: ItemIcon.item17 },
//   { name: '18', icon: ItemIcon.item18 },
//   { name: '19', icon: ItemIcon.item19 },
//   { name: '20', icon: ItemIcon.item20 },
//   { name: '21', icon: ItemIcon.item21 },
//   { name: '22', icon: ItemIcon.item22 },
//   { name: '23', icon: ItemIcon.item23 },
//   { name: '24', icon: ItemIcon.item24 },
//   { name: '25', icon: ItemIcon.item25 },
//   { name: '26', icon: ItemIcon.item26 },
//   { name: '27', icon: ItemIcon.item27 },
//   { name: '28', icon: ItemIcon.item28 },
//   { name: '29', icon: ItemIcon.item29 },
//   { name: '30', icon: ItemIcon.item30 },
//   { name: '31', icon: ItemIcon.item31 },
//   { name: '32', icon: ItemIcon.item32 },
//   { name: '33', icon: ItemIcon.item33 },
//   { name: '34', icon: ItemIcon.item34 },
//   { name: '35', icon: ItemIcon.item35 },
//   { name: '36', icon: ItemIcon.item36 },
//   { name: '37', icon: ItemIcon.item37 },
//   { name: '38', icon: ItemIcon.item38 },
//   { name: '39', icon: ItemIcon.item39 },
//   { name: '40', icon: ItemIcon.item40 },
//   { name: '41', icon: ItemIcon.item41 },
//   { name: '42', icon: ItemIcon.item42 },
//   { name: '43', icon: ItemIcon.item43 },
//   { name: '44', icon: ItemIcon.item44 },
// ]
