import RuneIcons from 'assets/runeIcons'

export const RUNE_LIST = {
  name: 'runes',
  type: 'checkbox',
  data: [
    { name: '1', label: `Apperentice's stone`, icon: RuneIcons.rune1 },
    { name: '2', label: `Hunter's Treasure`, icon: RuneIcons.rune2 },
    { name: '3', label: `Regeneration Rune`, icon: RuneIcons.rune3 },
    { name: '4', label: 'Astral Rune', icon: RuneIcons.rune4 },
    { name: '5', label: `Wicked Charm`, icon: RuneIcons.rune5 },
    { name: '6', label: `Ancestor's Relic`, icon: RuneIcons.rune6 },
    { name: '7', label: 'Juxtapose Chipped', icon: RuneIcons.rune7 },
    { name: '8', label: 'Guardian Sign', icon: RuneIcons.rune8 },
    { name: '9', label: 'Lionheart', icon: RuneIcons.rune9 },
    { name: '10', label: `Joomong's Eyelash`, icon: RuneIcons.rune10 },
    { name: '11', label: `Chain Lightning Rune`, icon: RuneIcons.rune11 },
    { name: '12', label: `Megamorph Sphere`, icon: RuneIcons.rune12 },
    { name: '13', label: `Multishot Rune`, icon: RuneIcons.rune13 },
    { name: '14', label: `Talisman of Demolition`, icon: RuneIcons.rune14 },
    { name: '15', label: `Inquisitor's Command`, icon: RuneIcons.rune15 },
    { name: '16', label: `Seal of Refraction`, icon: RuneIcons.rune16 },
    { name: '17', label: `Icewind Talon`, icon: RuneIcons.rune17 },
    { name: '18', label: `Magic Critical Rune`, icon: RuneIcons.rune18 },
    { name: '19', label: `Critical Block Rune`, icon: RuneIcons.rune19 },
    { name: '20', label: `Frost Armor Rune`, icon: RuneIcons.rune20 },
    // { name: '21', label: `Heal Aura Rune`, icon: '' },
    // { name: '22', label: `Luck Rune`, icon: '' },
    // { name: '23', label: `Silence Rune`, icon: '' },
    // { name: '24', label: `Mana Enlargement Rune`, icon: '' },
    // { name: '25', label: `Magic Resistance Rune`, icon: '' },
    // { name: '26', label: `Anti Disablity Rune`, icon: '' },
    // { name: '27', label: `Up! Rune`, icon: '' },
    // { name: '28', label: `Health Rune`, icon: '' },
    // { name: '29', label: `Ability Block Rune`, icon: '' },
    // { name: '30', label: `Damage Trap Rune`, icon: '' },
    // { name: '31', label: `Slow Trap Rune`, icon: '' },
    // { name: '32', label: `Rune of Mastery`, icon: '' },
    // { name: '33', label: `Berserker Orb`, icon: '' },
    // { name: '34', label: `Angel's Blessing`, icon: '' },
  ],
}
