import {BountyConfig} from './types'

export const addressBounty = {
  bronze: {
    name: 'bronze',
    address: {
      97: '0x7a8438Ec3236067F27d1687836C437Eb15ee2671',
      56: '0xc2eb593efa0a79e0ca620a11eb24eb5a43261ee8',
    },
  },
  silver: {
    name: 'silver',
    address: {
      97: '0x9d4a175e4e684434d109310DF288186287055aAa',
      56: '0x6EDD39b4Ba2fa53Db5f486908F19cB65905f04d9',
    },
  },
  gold: {
    name: 'gold',
    address: {
      97: '0x4f30851064757E9Ca7C6de8B4D7DCa4F35106bFD',
      56: '0xe3f637dB6b90cDc58894B0f8e74f657a9AB3a77c',
    },
  },
  sapphire: {
    name: 'sapphzire',
    address: {
      97: '0x1fb377516078eD066d2f32B99CB9e0b008825C6f',
      56: '0x5660CDd00b1C27f9b297d56665Ec66dcdAD4D3E0',
    },
  },
  ruby: {
    name: 'ruby',
    address: {
      97: '0x5aC3A6A11701944E19c911d3F78aea7Aa47c6aF0',
      56: '0xF70956b483D83258Ec012d098C4B92ed6c0056dF',
    },
  },
}

export const addressBox = {
  common: {
    name: 'common',
    address: {
      97: '0x7a8438Ec3236067F27d1687836C437Eb15ee2671',
      56: '0xc2eb593efa0a79e0ca620a11eb24eb5a43261ee8',
    },
  },
  rare: {
    name: 'rare',
    address: {
      97: '0x9d4a175e4e684434d109310DF288186287055aAa',
      56: '0x6EDD39b4Ba2fa53Db5f486908F19cB65905f04d9',
    },
  },
  epic: {
    name: 'epic',
    address: {
      97: '0x4f30851064757E9Ca7C6de8B4D7DCa4F35106bFD',
      56: '0xe3f637dB6b90cDc58894B0f8e74f657a9AB3a77c',
    },
  },
  legendary: {
    name: 'legendary',
    address: {
      97: '0x1fb377516078eD066d2f32B99CB9e0b008825C6f',
      56: '0x5660CDd00b1C27f9b297d56665Ec66dcdAD4D3E0',
    },
  },
}

const bounties: BountyConfig[] = [
  {
    id: 1,
    slug: 'bronze',
    title: 'HEROESTD BRONZE',
    description: 'Heroes TD Bounty First Drop is available. The higher-level Bounty, the more benefits you get.',
    symbol: 'HTDBRONZE',
    taskSteps: [
      'Submit your BSC Wallet Address',
      'Join Our Telegram Community',
      'Subscribe Our Telegram Announcement',
      'Submit one of your today comment link by using HeroesTD Stickers on our latest Telegram Announcement',
      'Visit HeroesTD on Youtube',
      'Follow @heroes_td on Twitter',
      'Read our Whitepaper',
      'Join Our Discord',
      'Retweet @heroes_td on Twitter',
      'Visit Heroestd on Facebook',
      'Refer Friends For Extra Entries',
    ],
    taskDesciptions: [
      'The number of slots available for each level of Bounty is limited.',
      'Check your level every day at 6 PM (UTC+7)',
      'The race will end on Nov 27, 2021',
    ],
    taskRequires: [],
    contractAddress: addressBounty.bronze.address,
    image: '/images/bounties/bronze_medal.png',
    endTime: 'UTC Nov 25th, 05:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'HEROESTD BRONZE NFT',
    linkTask: 'https://gleam.io/competitions/Bqm8H-heroestd-bounty',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Anub.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/bounty_frames/f_Bronze.png',
    desciptionHero: `Users with Ruby and Sapphire Bounty will earn an extra IDO Bounty for IDO Whitelist.
    Users with Ruby Bounty get an extra NFT Bounty for an NFT Hero Blind Box event slot.`,
    type: 'htd',
  },
  {
    id: 2,
    slug: 'silver',
    title: 'HEROESTD SILVER',
    description: 'Heroes TD Bounty First Drop is available. The higher-level Bounty, the more benefits you get.',
    symbol: 'HTDSILVER',
    linkTask: 'https://gleam.io/competitions/Bqm8H-heroestd-bounty',
    taskSteps: [
      'Submit your BSC Wallet Address',
      'Join Our Telegram Community',
      'Subscribe Our Telegram Announcement',
      'Submit one of your today comment link by using HeroesTD Stickers on our latest Telegram Announcement',
      'Visit HeroesTD on Youtube',
      'Follow @heroes_td on Twitter',
      'Read our Whitepaper',
      'Join Our Discord',
      'Retweet @heroes_td on Twitter',
      'Visit Heroestd on Facebook',
      'Refer Friends For Extra Entries',
    ],
    taskDesciptions: [
      'The number of slots available for each level of Bounty is limited.',
      'Check your level every day at 6 PM (UTC+7)',
      'The race will end on Nov 27, 2021',
    ],
    taskRequires: [],
    contractAddress: addressBounty.silver.address,
    image: '/images/bounties/silver_medal.png',
    endTime: 'UTC Nov 25th, 05:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'HEROESTD SILVER NFT',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/X.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/bounty_frames/f_Silver.png',
    desciptionHero: `Users with Ruby and Sapphire Bounty will earn an extra IDO Bounty for IDO Whitelist.
    Users with Ruby Bounty get an extra NFT Bounty for an NFT Hero Blind Box event slot.`,
    type: 'htd',
  },
  {
    id: 3,
    slug: 'gold',
    title: 'HEROESTD GOLD',
    description: 'Heroes TD Bounty First Drop is available. The higher-level Bounty, the more benefits you get.',
    symbol: 'HTDGOLD',
    linkTask: 'https://gleam.io/competitions/Bqm8H-heroestd-bounty',
    taskSteps: [
      'Submit your BSC Wallet Address',
      'Join Our Telegram Community',
      'Subscribe Our Telegram Announcement',
      'Submit one of your today comment link by using HeroesTD Stickers on our latest Telegram Announcement',
      'Visit HeroesTD on Youtube',
      'Follow @heroes_td on Twitter',
      'Read our Whitepaper',
      'Join Our Discord',
      'Retweet @heroes_td on Twitter',
      'Visit Heroestd on Facebook',
      'Refer Friends For Extra Entries',
    ],
    taskDesciptions: [
      'The number of slots available for each level of Bounty is limited.',
      'Check your level every day at 6 PM (UTC+7)',
      'The race will end on Nov 27, 2021',
    ],
    taskRequires: [],
    contractAddress: addressBounty.gold.address,
    image: '/images/bounties/gold_medal.png',
    endTime: 'UTC Nov 25th, 05:00 AM',
    totalClaimed: 0,
    totalLimit: 2640,
    nameNFT: 'HEROESTD GOLD NFT',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Bigboss.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/bounty_frames/f_Gold.png',
    desciptionHero: `Users with Ruby and Sapphire Bounty will earn an extra IDO Bounty for IDO Whitelist.
    Users with Ruby Bounty get an extra NFT Bounty for an NFT Hero Blind Box event slot.`,
    type: 'htd',
  },
  {
    id: 4,
    slug: 'sapphire',
    title: 'HEROESTD SAPPHIRE',
    description: 'Heroes TD Bounty First Drop is available. The higher-level Bounty, the more benefits you get.',
    symbol: 'HTDSAPPHIRE',
    linkTask: 'https://gleam.io/competitions/Bqm8H-heroestd-bounty',
    taskSteps: [
      'Submit your BSC Wallet Address',
      'Join Our Telegram Community',
      'Subscribe Our Telegram Announcement',
      'Submit one of your today comment link by using HeroesTD Stickers on our latest Telegram Announcement',
      'Visit HeroesTD on Youtube',
      'Follow @heroes_td on Twitter',
      'Read our Whitepaper',
      'Join Our Discord',
      'Retweet @heroes_td on Twitter',
      'Visit Heroestd on Facebook',
      'Refer Friends For Extra Entries',
    ],
    taskDesciptions: [
      'The number of slots available for each level of Bounty is limited.',
      'Check your level every day at 6 PM (UTC+7)',
      'The race will end on Nov 27, 2021',
    ],
    taskRequires: [],
    contractAddress: addressBounty.sapphire.address,
    image: '/images/bounties/sapphire_medal.png',
    endTime: 'UTC Nov 25th, 05:00 AM',
    totalClaimed: 0,
    totalLimit: 610,
    nameNFT: 'HEROESTD SAPPHIRE NFT',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Hunken.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/bounty_frames/f_Sapphire.png',
    desciptionHero: `Users with Ruby and Sapphire Bounty will earn an extra IDO Bounty for IDO Whitelist.
    Users with Ruby Bounty get an extra NFT Bounty for an NFT Hero Blind Box event slot.`,
    type: 'htd',
  },
  {
    id: 5,
    slug: 'ruby',
    title: 'HEROESTD RUBY',
    description: 'Heroes TD Bounty First Drop is available. The higher-level Bounty, the more benefits you get.',
    symbol: 'HTDRUBY',
    linkTask: 'https://gleam.io/competitions/Bqm8H-heroestd-bounty',
    taskSteps: [
      'Submit your BSC Wallet Address',
      'Join Our Telegram Community',
      'Subscribe Our Telegram Announcement',
      'Submit one of your today comment link by using HeroesTD Stickers on our latest Telegram Announcement',
      'Visit HeroesTD on Youtube',
      'Follow @heroes_td on Twitter',
      'Read our Whitepaper',
      'Join Our Discord',
      'Retweet @heroes_td on Twitter',
      'Visit Heroestd on Facebook',
      'Refer Friends For Extra Entries',
    ],
    taskDesciptions: [
      'The number of slots available for each level of Bounty is limited.',
      'Check your level every day at 6 PM (UTC+7)',
      'The race will end on Nov 27, 2021',
    ],
    taskRequires: [],
    contractAddress: addressBounty.ruby.address,
    image: '/images/bounties/ruby_medal.png',
    endTime: 'UTC Nov 25th, 05:00 AM',
    totalClaimed: 0,
    totalLimit: 140,
    nameNFT: 'HEROESTD RUBY NFT',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Amuka.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/bounty_frames/f_Ruby.png',
    desciptionHero: `Users with Ruby and Sapphire Bounty will earn an extra IDO Bounty for IDO Whitelist.
    Users with Ruby Bounty get an extra NFT Bounty for an NFT Hero Blind Box event slot.`,
    type: 'htd',
  },

  /* Community Config */
  {
    id: 6,
    slug: 'alphamoon-capital',
    title: 'AlphaMoon Capital - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDAlpha',
    linkTask: 'https://gleam.io/lWX9X/alphamoon-community-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x22695673b3fF1e4B066648258C5cE3597c325fD0',
      56: '0xeba18391d4419e3c4241e3c502d56f9a88abcfb7',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/AlphaMoonCapital.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'AlphaMoon FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/X.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_AlphaMoonCapital.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 7,
    slug: 'bbg',
    title: 'BBG - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDBBG',
    linkTask: 'https://gleam.io/DyGGi/bbg-community-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x2cC2Ff138c4A74658437e2c71127B9B953A35928',
      56: '0xe9B1EBc4Aaf7653dfeEDD63Be5e222364f659202',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Beng_Beng.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'BBG FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Hunken.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_BBG.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 8,
    slug: 'bscs',
    title: 'BSCS - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDBSC',
    linkTask: 'https://gleam.io/P8MAx/bsc-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x35702c8dC40Af13d51962Db09743eBe638889291',
      56: '0x61Be5cF44FFBD1B981FaD8Ff4960213428A03052',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/BSCS.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'BSC FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/X.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_BSC.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 9,
    slug: 'barmy',
    title: 'Barmy - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDBarmy',
    linkTask: 'https://gleam.io/3WDya/barmy-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xea589F7B4F0e105b2952F6eb3d0B962BA70b9C26',
      56: '0xEEd5BA5BFF2Dd651BC77A06A5Ab1950a105a165C',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Barmy.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Barmy FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Lucia.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Barmy.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 10,
    slug: 'bcoin',
    title: 'Bcoin - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDBcoin',
    linkTask: 'https://gleam.io/D3E2w/bcoin-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x27F88cde1Ea9e850A4542CfAC4569278867f6aC7',
      56: '0x31C6f064073C7846824Ff28E6b44d8a989185167',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Bcoin.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Bcoin FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Lucia.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Bcoin.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 11,
    slug: 'bunicorn',
    title: 'Bunicorn - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDBuni',
    linkTask: 'https://gleam.io/vDm1N/bunicorn-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x122A27f5B2D9C9ff59540b2d57695496b0d9Aa3E',
      56: '0x00ad09F04F468eD131FB13374B78399b596Ac3B7',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Bunicorn.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Bunicorn FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Hunken.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Bunicorn.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 12,
    slug: 'crvncapital',
    title: 'CRVNCapital - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDCRVN',
    linkTask: 'https://gleam.io/CUpdF/crvn-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xaCE17b09C5a7D1ffb1cEDcC132468B89bdc512Ab',
      56: '0xE61B1dB2b9D1D09DD2f5480F24ad93AA2837D0d7',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/CryptoLeak.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'CRVNCapital FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Amuka.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_CRVNCapital.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 13,
    slug: 'deo',
    title: 'DEO - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDDEO',
    linkTask: 'https://gleam.io/qKVhF/deo-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xf5b1d7577676DB3cba9De0C13b93B5DA34dbDe1c',
      56: '0x57484575718Bc8320C92fBFcaEa898592f82a881',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/DEO.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'DEO FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Bigboss.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_DEO.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 14,
    slug: 'dts',
    title: 'DTS - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDDTS',
    linkTask: 'https://gleam.io/SoT0g/dts-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x54F6c9B1FC45916646290ae68daE7CE138288BB3',
      56: '0x36EfceBf63B38bAc015bdF4DC96F924BfF6E5d00',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/DTS.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'DTS FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Anub.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_DTS.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 15,
    slug: 'kardia',
    title: 'Kardia - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDKAI',
    linkTask: 'https://gleam.io/Y4jI7/kardia-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x1a175222DC29d0Ea95887f66A4f3544D84e250A2',
      56: '0x890d95824A5781C2e260c42f4a5e1b7E0390339a',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/KardiaVenture.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Kardia FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Anub.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Kardia.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 16,
    slug: 'launchzone',
    title: 'LaunchZone - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDLZ',
    linkTask: 'https://gleam.io/M2TMr/launchzone-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x3a77D6a6aBd5f291F1f1F0d8ad833a2107AB8b08',
      56: '0x52F2FE3eBae52e4447b5C784e5B7fe9AbC293895',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Lz_pad.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'LaunchZone FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Brisingr.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_LaunchZone.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 17,
    slug: 'livetrade',
    title: 'Livetrade - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDLTD',
    linkTask: 'https://gleam.io/m5M5Y/livetrade-community-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xF988B6B54A267F92419dA59d15f9000409B59386',
      56: '0xfdfDF7031d01192Dd07DC13B2bcA3803790936f2',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/LiveTrade.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Livetrade FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Bigboss.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Livetrade.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 18,
    slug: 'monihub',
    title: 'Monihub - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDMONI',
    linkTask: 'https://gleam.io/Rz02F/monihub-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xb44de7Ab79Fb4b1b904cf25CA290cb42634B049C',
      56: '0x5E1042d49421138a774E0658C36624A9C048CB7B',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Monihub.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Monihub FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Amuka.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Monihub.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 19,
    slug: 'nuly',
    title: 'Nuly - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDNuly',
    linkTask: 'https://gleam.io/Cjaem/nuly-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x8b6e84E7F0B25178f0C2874B638784c6BF8256b3',
      56: '0x5Be315DB1D6f4A027359F81C9BeDe842aa1a46AB',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Nuly_Ventures.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Nuly FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Yol.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Nuly.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 20,
    slug: 'onus',
    title: 'ONUS - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDOnus',
    linkTask: 'https://gleam.io/3bZ9v/vndc-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x8a7EBe9a2c62468d7fa11bABCF1ca4cACfE140c6',
      56: '0x17f90e2f40f76685151c8aA25b8b322c7007e1FD',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/onus.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'ONUS FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Brisingr.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Onus.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
  },
  {
    id: 21,
    slug: 'wildcat',
    title: 'Wildcat - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDWildcat',
    linkTask: 'https://gleam.io/b77YM/wildcat-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xAC971a18FD378dab860C5092AABa927f12487098',
      56: '0x3ED8B9cE66e8D96bB189F75DA00FF624b4ff3147',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/WildCatVenture.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Wildcat FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Yol.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_WILDCAT.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 22,
    slug: 'jlaunchpad',
    title: 'Jlaunchpad - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDJLpad',
    linkTask: 'https://gleam.io/PQCHl/jlaunchpad-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x8f4C76996B5f36fC6159a30772832EA8B1908585',
      56: '0xe6f04ba84bDE0Acec5aa933B1a130f7b639502b6',
    },
    image: 'https://storage.googleapis.com/cdn.heroestd.io/NFT_Bounty/Community/icon/Launchpad.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Jlaunchpad FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/X.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Lauchpad.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 23,
    slug: 'mexc',
    title: 'MEXC - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDMEXC',
    linkTask: 'https://gleam.io/GXJ9h/mexc-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x415fbeDE558DdD445EDa690b256878a499fBE610',
      56: '0x2B5b1Fb2D24B1611b82e37d517F6329112CeF266',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Mexs.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'MEXC FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Hunken.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Mexc.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 24,
    slug: 'kiwigroup',
    title: 'KiwiGroup - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDKiwi',
    linkTask: 'https://gleam.io/xKY0x/kiwigroup-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x1725375AeBFa2fE8E925Abef9EC646b232535A0e',
      56: '0xD7EdaE32acF6E6127bAB3b1d1c3Ae914aD5cAE34',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/KIWI.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'KiwiGroup FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Brisingr.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Kiwi.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 25,
    slug: 'ptom',
    title: 'Ptom - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDKiwi',
    linkTask: 'https://gleam.io/jZ05b/ptom-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x119aE6Fb5e254908f51808a7e506D59A38993a80',
      56: '0x9255d825A030acDF6ce053B6EF3eE8da84fD87Ac',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Phantom.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Ptom FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Brisingr.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Phantom.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 26,
    slug: 'lucky-ventures',
    title: 'Lucky Ventures - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDLucky',
    linkTask: 'https://gleam.io/mP5eW/fam-central-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xcA8c0fB260322229076BdA9627c678818ddAE5cf',
      56: '0xC966e0661198D812F2F014368d8900b8c4aC7934',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/LuckyVentures.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Lucky Ventures FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Yol.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_LuckyVentures.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 27,
    slug: 'senspark',
    title: 'Senspark - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDSPank',
    linkTask: 'https://gleam.io/iqZCH/senspark-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x5660CDd00b1C27f9b297d56665Ec66dcdAD4D3E0',
      56: '0xaC6a1B3F41607F293F16eCD53F59767fef14230D',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/SensparkVENTURES.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Senspark FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Lucia.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Senspark.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: true,
  },
  {
    id: 28,
    slug: 'tccl',
    title: 'TCCL - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDSPank',
    linkTask: 'https://gleam.io/WnOdu/tccl-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xe3f637dB6b90cDc58894B0f8e74f657a9AB3a77c',
      56: '0xa09cd9439a7cB983985CA9b45E47C8F046F7513c',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/TCCL.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'TCCL FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Hunken.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_TCCL.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 29,
    slug: 'the-light-house',
    title: 'The Light House - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDLHouse',
    linkTask: 'https://gleam.io/BsYpD/the-light-house-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xab7cbb3Df6438a50B509e010879838B87De7125f',
      56: '0xcD736eEb97DD14192D8334E6655316aA871be2E0',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Lighthouse.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'The Light House FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Yol.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Lighthouse.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 30,
    slug: 'coin-lab',
    title: 'CoinLab - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDCoinLab',
    linkTask: 'https://gleam.io/onyNK/coinlab-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0x905440Ce9e11cE6DdAdC41499fA476eda61F3ae1',
      56: '0x5248739d1FB6c67372Bf1661E1Ba8E36781B991b',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/CoinLAB.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'CoinLab FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/X.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_CoinLab.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
  {
    id: 31,
    slug: 'rada',
    title: 'Rada - HEROESTD FRIENDSTER BOUNTY',
    description: `The beautiful bounty and will be used to represent to one specific community! 
    This bounty can help you to connect new friend and your community easily - together we can win`,
    symbol: 'HTDRada',
    linkTask: 'https://gleam.io/mE6n7/rada-friendster-bounty',
    taskSteps: [
      'Submit BSC Wallet',
      'Join Telegram Community',
      'Subscribe Telegram Announcement',
      'Follow Twitter',
      'Refer',
    ],
    taskDesciptions: [
      'The number of slots available for FRIENDSTER Bounty is available for every one in your community! ',
      'Please refer your friend to claim together - More Friend - More Fun!',
      'The race will end in Nov 25th, 2021',
    ],
    taskRequires: [],
    contractAddress: {
      97: '0xb797947f8a802a8708B5C78b4C83a65a7A069325',
      56: '0x5F6AAE66802cb65b20212f2591cC44eE6F4B94a7',
    },
    image: 'https://cdn.heroestd.io/NFT_Bounty/Community/icon/Rada.png',
    endTime: 'UTC Nov 25th, 02:00 AM',
    totalClaimed: 0,
    totalLimit: -1,
    nameNFT: 'Rada FRIENDSTER BOUNTY',
    heroVideo: 'https://cdn.heroestd.io/NFT_Bounty/Community/video/Lucia.mp4',
    framesImage: 'https://cdn.heroestd.io/NFT_Bounty/Community/frames/f_Rada.png',
    desciptionHero: `Who can claim a FRIENDSTER Bounty? Everyone in your Community.
    How can I claim this bounty? Who joined our partnership community (Eg: Kai, LZ, Onus, WildCat etc..) Finish your Gleam.io Mission which will be pinned on your Community Telegram Group`,
    type: 'community',
    background: false,
  },
]

export default bounties
